[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio", "uuid", "macros"] }
uuid = { version = "1.24.1", features = ["v4", "fast-rng", "macro-diagnostics"] }

configuration = { path = "../configuration/" }
subtitles = { path = "../subtitles/"}
