TXT_CONTENTS = [
    "Que si me escribes y no contesto",
    "Tú no te ofendas si no aparezco",
    "El sentimiento yo no lo presto",
    "Es que no soy de nadie, no soy dueto",
    "Please don't take it personal (nah, nah, nah, nah, nah, yeah)",
    "If I don't check up here through the phone, woah",
    "Me dicen bipolar",
    "Porque un día quiero todo",
    "Pero al otro ya no me interesa verte más, ah-ah",
    "Me dicen bipolar",
    "A veces fuego, a veces frío",
    "A vecеs noche, a veces día",
    "Pеro soy real, ah-ah",
    "Vengo, me voy ya",
    "Yo sé cómo soy, va",
    "I know that I got issues, that's the truth",
    "And if you get offended, that's on you",
    "Every emotion I felt that times two",
    "It hurts when you play to lose",
    "Been burned and I've been accused, yeah-yeah, yeh, yeh, eh",
    "Me dicen bipolar",
    "Porque un día quiero todo",
    "Pero al otro ya no me interesa verte más, ah-ah (yeh, yeh, yeh)",
    "Me dicen bipolar",
    "A veces fuego, a veces frío",
    "A veces noche, a veces día",
    "Pero soy real, ah-ah (nah, nah, nah, nah, nah, nah)",
    "Que si me escribes y no contesto",
    "Tú no te ofendas si no aparezco",
    "Mi sentimiento yo no lo presto",
    "Es que no soy de nadie, no soy dueto",
    "Please don't take it personal (nah, nah, nah, nah, nah)",
    "If I don't check up here through the phone, woah",
    "Me dicen bipolar",
    "Porque un día quiero todo",
    "Pero al otro ya no me interesa verte más, ah-ah (yeh, yeh, yeh)",
    "Me dicen bipolar",
    "A veces fuego, a veces frío",
    "A veces noche, a veces día",
    "Pero soy real, ah-ah (nah, nah, nah, nah, nah, nah)",
    "Me dicen bipolar",
    "Porque un día quiero todo",
    "Pero al otro ya no me interesa verte más, ah, ah-ah (yeh, yeh, yeh)",
    "Me dicen bipolar",
    "A veces fuego, a veces frío",
    "A veces noche, a veces día",
    "Pero soy real, ah-ah (nah, nah, nah, nah, nah, nah, nah)",
]

