use std::{
    fmt::{Display, Formatter},
    str::FromStr,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Language {
    Esperanto,
    English,
    Russian,
    Mandarin,
    Spanish,
    Portuguese,
    Italian,
    Bengali,
    French,
    German,
    Ukrainian,
    Georgian,
    Arabic,
    Hindi,
    Japanese,
    Hebrew,
    Yiddish,
    Polish,
    Amharic,
    Javanese,
    Korean,
    Bokmal,
    Danish,
    Swedish,
    Finnish,
    Turkish,
    Dutch,
    Hungarian,
    Czech,
    Greek,
    Bulgarian,
    Belarusian,
    Marathi,
    Kannada,
    Romanian,
    Slovene,
    Croatian,
    Serbian,
    Macedonian,
    Lithuanian,
    Latvian,
    Estonian,
    Tamil,
    Vietnamese,
    Urdu,
    Thai,
    Gujarati,
    Uzbek,
    Punjabi,
    Azerbaijani,
    Indonesian,
    Telugu,
    Persian,
    Malayalam,
    Oriya,
    Burmese,
    Nepali,
    Sinhalese,
    Khmer,
    Turkmen,
    Akan,
    Zulu,
    Shona,
    Afrikaans,
    Latin,
    Slovak,
    Catalan,
    Tagalog,
    Armenian,
    Welsh,
}

impl Display for Language {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_name())
    }
}

impl From<whatlang::Lang> for Language {
    fn from(lang: whatlang::Lang) -> Self {
        match lang {
            whatlang::Lang::Epo => Self::Esperanto,
            whatlang::Lang::Eng => Self::English,
            whatlang::Lang::Rus => Self::Russian,
            whatlang::Lang::Cmn => Self::Mandarin,
            whatlang::Lang::Spa => Self::Spanish,
            whatlang::Lang::Por => Self::Portuguese,
            whatlang::Lang::Ita => Self::Italian,
            whatlang::Lang::Ben => Self::Bengali,
            whatlang::Lang::Fra => Self::French,
            whatlang::Lang::Deu => Self::German,
            whatlang::Lang::Ukr => Self::Ukrainian,
            whatlang::Lang::Kat => Self::Georgian,
            whatlang::Lang::Ara => Self::Arabic,
            whatlang::Lang::Hin => Self::Hindi,
            whatlang::Lang::Jpn => Self::Japanese,
            whatlang::Lang::Heb => Self::Hebrew,
            whatlang::Lang::Yid => Self::Yiddish,
            whatlang::Lang::Pol => Self::Polish,
            whatlang::Lang::Amh => Self::Amharic,
            whatlang::Lang::Jav => Self::Javanese,
            whatlang::Lang::Kor => Self::Korean,
            whatlang::Lang::Nob => Self::Bokmal,
            whatlang::Lang::Dan => Self::Danish,
            whatlang::Lang::Swe => Self::Swedish,
            whatlang::Lang::Fin => Self::Finnish,
            whatlang::Lang::Tur => Self::Turkish,
            whatlang::Lang::Nld => Self::Dutch,
            whatlang::Lang::Hun => Self::Hungarian,
            whatlang::Lang::Ces => Self::Czech,
            whatlang::Lang::Ell => Self::Greek,
            whatlang::Lang::Bul => Self::Bulgarian,
            whatlang::Lang::Bel => Self::Belarusian,
            whatlang::Lang::Mar => Self::Marathi,
            whatlang::Lang::Kan => Self::Kannada,
            whatlang::Lang::Ron => Self::Romanian,
            whatlang::Lang::Slv => Self::Slovene,
            whatlang::Lang::Hrv => Self::Croatian,
            whatlang::Lang::Srp => Self::Serbian,
            whatlang::Lang::Mkd => Self::Macedonian,
            whatlang::Lang::Lit => Self::Lithuanian,
            whatlang::Lang::Lav => Self::Latvian,
            whatlang::Lang::Est => Self::Estonian,
            whatlang::Lang::Tam => Self::Tamil,
            whatlang::Lang::Vie => Self::Vietnamese,
            whatlang::Lang::Urd => Self::Urdu,
            whatlang::Lang::Tha => Self::Thai,
            whatlang::Lang::Guj => Self::Gujarati,
            whatlang::Lang::Uzb => Self::Uzbek,
            whatlang::Lang::Pan => Self::Punjabi,
            whatlang::Lang::Aze => Self::Azerbaijani,
            whatlang::Lang::Ind => Self::Indonesian,
            whatlang::Lang::Tel => Self::Telugu,
            whatlang::Lang::Pes => Self::Persian,
            whatlang::Lang::Mal => Self::Malayalam,
            whatlang::Lang::Ori => Self::Oriya,
            whatlang::Lang::Mya => Self::Burmese,
            whatlang::Lang::Nep => Self::Nepali,
            whatlang::Lang::Sin => Self::Sinhalese,
            whatlang::Lang::Khm => Self::Khmer,
            whatlang::Lang::Tuk => Self::Turkmen,
            whatlang::Lang::Aka => Self::Akan,
            whatlang::Lang::Zul => Self::Zulu,
            whatlang::Lang::Sna => Self::Shona,
            whatlang::Lang::Afr => Self::Afrikaans,
            whatlang::Lang::Lat => Self::Latin,
            whatlang::Lang::Slk => Self::Slovak,
            whatlang::Lang::Cat => Self::Catalan,
            whatlang::Lang::Tgl => Self::Tagalog,
            whatlang::Lang::Hye => Self::Armenian,
            whatlang::Lang::Cym => Self::Welsh,
        }
    }
}

impl Language {
    /// Returns the English name of the language.
    pub const fn as_name(self) -> &'static str {
        match self {
            Self::Esperanto => "Esperanto",
            Self::English => "English",
            Self::Russian => "Russian",
            Self::Mandarin => "Mandarin",
            Self::Spanish => "Spanish",
            Self::Portuguese => "Portuguese",
            Self::Italian => "Italian",
            Self::Bengali => "Bengali",
            Self::French => "French",
            Self::German => "German",
            Self::Ukrainian => "Ukrainian",
            Self::Georgian => "Georgian",
            Self::Arabic => "Arabic",
            Self::Hindi => "Hindi",
            Self::Japanese => "Japanese",
            Self::Hebrew => "Hebrew",
            Self::Yiddish => "Yiddish",
            Self::Polish => "Polish",
            Self::Amharic => "Amharic",
            Self::Javanese => "Javanese",
            Self::Korean => "Korean",
            Self::Bokmal => "Bokmål",
            Self::Danish => "Danish",
            Self::Swedish => "Swedish",
            Self::Finnish => "Finnish",
            Self::Turkish => "Turkish",
            Self::Dutch => "Dutch",
            Self::Hungarian => "Hungarian",
            Self::Czech => "Czech",
            Self::Greek => "Greek",
            Self::Bulgarian => "Bulgarian",
            Self::Belarusian => "Belarusian",
            Self::Marathi => "Marathi",
            Self::Kannada => "Kannada",
            Self::Romanian => "Romanian",
            Self::Slovene => "Slovene",
            Self::Croatian => "Croatian",
            Self::Serbian => "Serbian",
            Self::Macedonian => "Macedonian",
            Self::Lithuanian => "Lithuanian",
            Self::Latvian => "Latvian",
            Self::Estonian => "Estonian",
            Self::Tamil => "Tamil",
            Self::Vietnamese => "Vietnamese",
            Self::Urdu => "Urdu",
            Self::Thai => "Thai",
            Self::Gujarati => "Gujarati",
            Self::Uzbek => "Uzbek",
            Self::Punjabi => "Punjabi",
            Self::Azerbaijani => "Azerbaijani",
            Self::Indonesian => "Indonesian",
            Self::Telugu => "Telugu",
            Self::Persian => "Persian",
            Self::Malayalam => "Malayalam",
            Self::Oriya => "Oriya",
            Self::Burmese => "Burmese",
            Self::Nepali => "Nepali",
            Self::Sinhalese => "Sinhalese",
            Self::Khmer => "Khmer",
            Self::Turkmen => "Turkmen",
            Self::Akan => "Akan",
            Self::Zulu => "Zulu",
            Self::Shona => "Shona",
            Self::Afrikaans => "Afrikaans",
            Self::Latin => "Latin",
            Self::Slovak => "Slovak",
            Self::Catalan => "Catalan",
            Self::Tagalog => "Tagalog",
            Self::Armenian => "Armenian",
            Self::Welsh => "Welsh",
        }
    }

    /// Returns the native name of the language.
    pub const fn as_native_name(self) -> &'static str {
        match self {
            Self::Esperanto => "Esperanto",
            Self::English => "English",
            Self::Russian => "Русский",
            Self::Mandarin => "普通话",
            Self::Spanish => "Español",
            Self::Portuguese => "Português",
            Self::Italian => "Italiano",
            Self::Bengali => "বাংলা",
            Self::French => "Français",
            Self::German => "Deutsch",
            Self::Ukrainian => "Українська",
            Self::Georgian => "ქართული",
            Self::Arabic => "العربية",
            Self::Hindi => "हिन्दी",
            Self::Japanese => "日本語",
            Self::Hebrew => "עברית",
            Self::Yiddish => "ייִדיש",
            Self::Polish => "Polski",
            Self::Amharic => "አማርኛ",
            Self::Javanese => "Basa Jawa",
            Self::Korean => "한국어",
            Self::Bokmal => "Bokmål",
            Self::Danish => "Dansk",
            Self::Swedish => "Svenska",
            Self::Finnish => "Suomi",
            Self::Turkish => "Türkçe",
            Self::Dutch => "Nederlands",
            Self::Hungarian => "Magyar",
            Self::Czech => "Čeština",
            Self::Greek => "Ελληνικά",
            Self::Bulgarian => "Български",
            Self::Belarusian => "Беларуская",
            Self::Marathi => "मराठी",
            Self::Kannada => "ಕನ್ನಡ",
            Self::Romanian => "Română",
            Self::Slovene => "Slovenščina",
            Self::Croatian => "Hrvatski",
            Self::Serbian => "Српски",
            Self::Macedonian => "Македонски",
            Self::Lithuanian => "Lietuvių",
            Self::Latvian => "Latviešu",
            Self::Estonian => "Eesti",
            Self::Tamil => "தமிழ்",
            Self::Vietnamese => "Tiếng Việt",
            Self::Urdu => "اُردُو",
            Self::Thai => "ภาษาไทย",
            Self::Gujarati => "ગુજરાતી",
            Self::Uzbek => "Oʻzbekcha",
            Self::Punjabi => "ਪੰਜਾਬੀ",
            Self::Azerbaijani => "Azərbaycanca",
            Self::Indonesian => "Bahasa Indonesia",
            Self::Telugu => "తెలుగు",
            Self::Persian => "فارسی",
            Self::Malayalam => "മലയാളം",
            Self::Oriya => "ଓଡ଼ିଆ",
            Self::Burmese => "မြန်မာစာ",
            Self::Nepali => "नेपाली",
            Self::Sinhalese => "සිංහල",
            Self::Khmer => "ភាសាខ្មែរ",
            Self::Turkmen => "Türkmençe",
            Self::Akan => "Akan",
            Self::Zulu => "IsiZulu",
            Self::Shona => "ChiShona",
            Self::Afrikaans => "Afrikaans",
            Self::Latin => "Lingua Latina",
            Self::Slovak => "Slovenčina",
            Self::Catalan => "Català",
            Self::Tagalog => "Tagalog",
            Self::Armenian => "Հայերեն",
            Self::Welsh => "Cymraeg",
        }
    }

    /// Returns the ISO 639-1 two-letter language code.
    pub const fn as_code_2(self) -> &'static str {
        match self {
            Self::Esperanto => "eo",
            Self::English => "en",
            Self::Russian => "ru",
            Self::Mandarin => "zh",
            Self::Spanish => "es",
            Self::Portuguese => "pt",
            Self::Italian => "it",
            Self::Bengali => "bn",
            Self::French => "fr",
            Self::German => "de",
            Self::Ukrainian => "uk",
            Self::Georgian => "ka",
            Self::Arabic => "ar",
            Self::Hindi => "hi",
            Self::Japanese => "ja",
            Self::Hebrew => "he",
            Self::Yiddish => "yi",
            Self::Polish => "pl",
            Self::Amharic => "am",
            Self::Javanese => "jv",
            Self::Korean => "ko",
            Self::Bokmal => "nb",
            Self::Danish => "da",
            Self::Swedish => "sv",
            Self::Finnish => "fi",
            Self::Turkish => "tr",
            Self::Dutch => "nl",
            Self::Hungarian => "hu",
            Self::Czech => "cs",
            Self::Greek => "el",
            Self::Bulgarian => "bg",
            Self::Belarusian => "be",
            Self::Marathi => "mr",
            Self::Kannada => "kn",
            Self::Romanian => "ro",
            Self::Slovene => "sl",
            Self::Croatian => "hr",
            Self::Serbian => "sr",
            Self::Macedonian => "mk",
            Self::Lithuanian => "lt",
            Self::Latvian => "lv",
            Self::Estonian => "et",
            Self::Tamil => "ta",
            Self::Vietnamese => "vi",
            Self::Urdu => "ur",
            Self::Thai => "th",
            Self::Gujarati => "gu",
            Self::Uzbek => "uz",
            Self::Punjabi => "pa",
            Self::Azerbaijani => "az",
            Self::Indonesian => "id",
            Self::Telugu => "te",
            Self::Persian => "fa",
            Self::Malayalam => "ml",
            Self::Oriya => "or",
            Self::Burmese => "my",
            Self::Nepali => "ne",
            Self::Sinhalese => "si",
            Self::Khmer => "km",
            Self::Turkmen => "tk",
            Self::Akan => "ak",
            Self::Zulu => "zu",
            Self::Shona => "sn",
            Self::Afrikaans => "af",
            Self::Latin => "la",
            Self::Slovak => "sk",
            Self::Catalan => "ca",
            Self::Tagalog => "tl",
            Self::Armenian => "hy",
            Self::Welsh => "cy",
        }
    }
}

impl Language {
    /// Returns the ISO 639-3 three-letter language code.
    pub const fn as_code_3(self) -> &'static str {
        match self {
            Self::Esperanto => "epo",
            Self::English => "eng",
            Self::Russian => "rus",
            Self::Mandarin => "cmn",
            Self::Spanish => "spa",
            Self::Portuguese => "por",
            Self::Italian => "ita",
            Self::Bengali => "ben",
            Self::French => "fra",
            Self::German => "deu",
            Self::Ukrainian => "ukr",
            Self::Georgian => "kat",
            Self::Arabic => "ara",
            Self::Hindi => "hin",
            Self::Japanese => "jpn",
            Self::Hebrew => "heb",
            Self::Yiddish => "yid",
            Self::Polish => "pol",
            Self::Amharic => "amh",
            Self::Javanese => "jav",
            Self::Korean => "kor",
            Self::Bokmal => "nob",
            Self::Danish => "dan",
            Self::Swedish => "swe",
            Self::Finnish => "fin",
            Self::Turkish => "tur",
            Self::Dutch => "nld",
            Self::Hungarian => "hun",
            Self::Czech => "ces",
            Self::Greek => "ell",
            Self::Bulgarian => "bul",
            Self::Belarusian => "bel",
            Self::Marathi => "mar",
            Self::Kannada => "kan",
            Self::Romanian => "ron",
            Self::Slovene => "slv",
            Self::Croatian => "hrv",
            Self::Serbian => "srp",
            Self::Macedonian => "mkd",
            Self::Lithuanian => "lit",
            Self::Latvian => "lav",
            Self::Estonian => "est",
            Self::Tamil => "tam",
            Self::Vietnamese => "vie",
            Self::Urdu => "urd",
            Self::Thai => "tha",
            Self::Gujarati => "guj",
            Self::Uzbek => "uzb",
            Self::Punjabi => "pan",
            Self::Azerbaijani => "aze",
            Self::Indonesian => "ind",
            Self::Telugu => "tel",
            Self::Persian => "pes",
            Self::Malayalam => "mal",
            Self::Oriya => "ori",
            Self::Burmese => "mya",
            Self::Nepali => "nep",
            Self::Sinhalese => "sin",
            Self::Khmer => "khm",
            Self::Turkmen => "tuk",
            Self::Akan => "aka",
            Self::Zulu => "zul",
            Self::Shona => "sna",
            Self::Afrikaans => "afr",
            Self::Latin => "lat",
            Self::Slovak => "slk",
            Self::Catalan => "cat",
            Self::Tagalog => "tgl",
            Self::Armenian => "hye",
            Self::Welsh => "cym",
        }
    }
}

impl FromStr for Language {
    type Err = String;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value.trim().to_lowercase().as_str() {
            "eo" | "epo" | "esperanto" => Ok(Self::Esperanto),
            "en" | "eng" | "english" => Ok(Self::English),
            "ru" | "rus" | "russian" | "русский" => Ok(Self::Russian),
            "zh" | "cmn" | "mandarin" | "普通话" => Ok(Self::Mandarin),
            "es" | "spa" | "spanish" | "español" => Ok(Self::Spanish),
            "pt" | "por" | "portuguese" | "português" => Ok(Self::Portuguese),
            "it" | "ita" | "italian" | "italiano" => Ok(Self::Italian),
            "bn" | "ben" | "bengali" | "বাংলা" => Ok(Self::Bengali),
            "fr" | "fra" | "french" | "français" => Ok(Self::French),
            "de" | "deu" | "german" | "deutsch" => Ok(Self::German),
            "uk" | "ukr" | "ukrainian" | "українська" => Ok(Self::Ukrainian),
            "ka" | "kat" | "georgian" | "ქართული" => Ok(Self::Georgian),
            "ar" | "ara" | "arabic" | "العربية" => Ok(Self::Arabic),
            "hi" | "hin" | "hindi" | "हिन्दी" => Ok(Self::Hindi),
            "ja" | "jpn" | "japanese" | "日本語" => Ok(Self::Japanese),
            "he" | "heb" | "hebrew" | "עברית" => Ok(Self::Hebrew),
            "yi" | "yid" | "yiddish" | "ייִדיש" => Ok(Self::Yiddish),
            "pl" | "pol" | "polish" | "polski" => Ok(Self::Polish),
            "am" | "amh" | "amharic" | "አማርኛ" => Ok(Self::Amharic),
            "jv" | "jav" | "javanese" | "basa jawa" => Ok(Self::Javanese),
            "ko" | "kor" | "korean" | "한국어" => Ok(Self::Korean),
            "nb" | "nob" | "bokmal" | "bokmål" => Ok(Self::Bokmal),
            "da" | "dan" | "danish" | "dansk" => Ok(Self::Danish),
            "sv" | "swe" | "swedish" | "svenska" => Ok(Self::Swedish),
            "fi" | "fin" | "finnish" | "suomi" => Ok(Self::Finnish),
            "tr" | "tur" | "turkish" | "türkçe" => Ok(Self::Turkish),
            "nl" | "nld" | "dutch" | "nederlands" => Ok(Self::Dutch),
            "hu" | "hun" | "hungarian" | "magyar" => Ok(Self::Hungarian),
            "cs" | "ces" | "czech" | "čeština" => Ok(Self::Czech),
            "el" | "ell" | "greek" | "ελληνικά" => Ok(Self::Greek),
            "bg" | "bul" | "bulgarian" | "български" => Ok(Self::Bulgarian),
            "be" | "bel" | "belarusian" | "беларуская" => Ok(Self::Belarusian),
            "mr" | "mar" | "marathi" | "मराठी" => Ok(Self::Marathi),
            "kn" | "kan" | "kannada" | "ಕನ್ನಡ" => Ok(Self::Kannada),
            "ro" | "ron" | "romanian" | "română" => Ok(Self::Romanian),
            "sl" | "slv" | "slovene" | "slovenščina" => Ok(Self::Slovene),
            "hr" | "hrv" | "croatian" | "hrvatski" => Ok(Self::Croatian),
            "sr" | "srp" | "serbian" | "српски" => Ok(Self::Serbian),
            "mk" | "mkd" | "macedonian" | "македонски" => Ok(Self::Macedonian),
            "lt" | "lit" | "lithuanian" | "lietuvių" => Ok(Self::Lithuanian),
            "lv" | "lav" | "latvian" | "latviešu" => Ok(Self::Latvian),
            "et" | "est" | "estonian" | "eesti" => Ok(Self::Estonian),
            "ta" | "tam" | "tamil" | "தமிழ்" => Ok(Self::Tamil),
            "vi" | "vie" | "vietnamese" | "tiếng việt" => Ok(Self::Vietnamese),
            "ur" | "urd" | "urdu" | "اُردُو" => Ok(Self::Urdu),
            "th" | "tha" | "thai" | "ภาษาไทย" => Ok(Self::Thai),
            "gu" | "guj" | "gujarati" | "ગુજરાતી" => Ok(Self::Gujarati),
            "uz" | "uzb" | "uzbek" | "oʻzbekcha" => Ok(Self::Uzbek),
            "pa" | "pan" | "punjabi" | "ਪੰਜਾਬੀ" => Ok(Self::Punjabi),
            "az" | "aze" | "azerbaijani" | "azərbaycanca" => Ok(Self::Azerbaijani),
            "id" | "ind" | "indonesian" | "bahasa indonesia" => Ok(Self::Indonesian),
            "te" | "tel" | "telugu" | "తెలుగు" => Ok(Self::Telugu),
            "fa" | "pes" | "persian" | "فارسی" => Ok(Self::Persian),
            "ml" | "mal" | "malayalam" | "മലയാളം" => Ok(Self::Malayalam),
            "or" | "ori" | "oriya" | "ଓଡ଼ିଆ" => Ok(Self::Oriya),
            "my" | "mya" | "burmese" | "မြန်မာစာ" => Ok(Self::Burmese),
            "ne" | "nep" | "nepali" | "नेपाली" => Ok(Self::Nepali),
            "si" | "sin" | "sinhalese" | "සිංහල" => Ok(Self::Sinhalese),
            "km" | "khm" | "khmer" | "ភាសាខ្មែរ" => Ok(Self::Khmer),
            "tk" | "tuk" | "turkmen" | "türkmençe" => Ok(Self::Turkmen),
            "ak" | "aka" | "akan" => Ok(Self::Akan),
            "zu" | "zul" | "zulu" | "isizulu" => Ok(Self::Zulu),
            "sn" | "sna" | "shona" | "chishona" => Ok(Self::Shona),
            "af" | "afr" | "afrikaans" => Ok(Self::Afrikaans),
            "la" | "lat" | "latin" | "lingua latina" => Ok(Self::Latin),
            "sk" | "slk" | "slovak" | "slovenčina" => Ok(Self::Slovak),
            "ca" | "cat" | "catalan" | "català" => Ok(Self::Catalan),
            "tl" | "tgl" | "tagalog" => Ok(Self::Tagalog),
            "hy" | "hye" | "armenian" | "հայերեն" => Ok(Self::Armenian),
            "cy" | "cym" | "welsh" | "cymraeg" => Ok(Self::Welsh),
            _ => Err(String::from("Language not in list")),
        }
    }
}
