[project]
name = "translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tyler Walters", email = "1twalters01@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "argostranslate>=1.11.0",
    "datasets>=5.0.1",
    "deepl>=1.32.0",
    "evaluate>=0.4.6",
    "google-cloud-translate>=3.27.0",
    "sacrebleu>=2.6.0",
    "transformers>=4.57.6",
]

[project.scripts]
translator = "translator:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

